CREATE TABLE MY_USER (id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(200) NOT NULL);

CREATE TABLE TASK (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT NOT NULL, completed BOOLEAN, content VARCHAR(2000));

ALTER TABLE TASK
    ADD CONSTRAINT task_user_id
        FOREIGN KEY (user_id) references MY_USER(id)